steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"
      - "."
    id: "Build image"
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"
    id: "Push to gcr.io"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"
      - "--region=asia-southeast2"
      - "--cpu=1"
      - "--memory=1024Mi"
      - "--allow-unauthenticated"
      - "--set-secrets=JWT_SECRET=jwt_secret:latest,DATABASE_URL=db_url:latest"
    id: "Deploy Project"
images:
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA"
