services:
  aquasense:
    build: .
    ports:
      - "8000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
  db:
    restart: always
    image: "mysql"
    env_file: .env
    ports:
      - "3308:3306"
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "db_aquasense"
      MYSQL_DB: "db_aquasense"
